# Generated by Django 4.2.17 on 2025-01-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='content',
            new_name='bio',
        ),
    ]
