# Generated by Django 4.2.17 on 2025-01-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_options_rename_content_about_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
